import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";

export const metadata = {
  title: "Ignite Techfest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className="fixed inset-0 -z-10">
          <div className="absolute inset-0 bg-[url('/assets/bg.png')] bg-cover bg-center" />
          <div className="absolute inset-0 bg-black opacity-60" />
        </div>
        {children}
      </body>
    </html>
  );
}
