import { Poppins } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/navbar";
import Collabration from "@/components/Collabration";
import ContactSection from "@/components/Contact";
import Incentive from "@/components/Incentive";
import About from "@/components/About"
export const metadata = {
  title: "Ignite Techfest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
       
        {children}
        <About />
        <Incentive/>
        <Collabration />
        <ContactSection />
        
        <footer>
          
        </footer>
      </body>
    </html>
  );
}
